name: ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: your-aws-region

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region your-aws-region | docker login --username AWS --password-stdin ${{ secrets.ECR_IMAGE }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ECR_IMAGE }} .
        docker push ${{ secrets.ECR_IMAGE }}

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} --service ${{ secrets.SERVICE_NAME }} --force-new-deployment
